version: '3'

services:
  expressst:
    build:
      
      context: ./express
      dockerfile: Dockerfile
    image: zaourzag/expresss
    container_name: api
    restart: unless-stopped
    ports:
      - "442:443"
      - "8080:8080"
    volumes:
        - ./assets:/home/site/wwwroot/assets
        - ./config:/etc/cloudflared
        - ./logs:/home/site/wwwroot/src/server/logs
    networks:
      - app-network

  nginxt:
   build:
    context: ./nginx
    dockerfile: Dockerfile
   image: zaourzag/nginx
   container_name: nginx-web-pokemon-api
   restart: unless-stopped
   ports:
      - "81:80"
      - "444:443"
  
   
   depends_on:
      - expressst
   networks:
      - app-network
volumes:
    web-root:

networks:
  app-network:
    driver: bridge
