version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs:16
    container_name: expresst
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:1.13
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/home/site/wwwroot
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf	
      - config/sshd_config:/etc/ssh/
   
    depends_on:
      - nodejs
    networks:
      - app-network

  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/site/wwwroot/
      o: bind

networks:
  app-network:
    driver: bridge
