version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs:16
    container_name: expresst
    restart: unless-stopped
    networks:
      - app-network

  webserver:
  
    image: nginx:1.13
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        source: web-root
        target: /wwwroot
        volume:
          nocopy: true
      - type: bind
        source: ./*
        target: /home/site/wwwroot/
      - type: bind
        source: ./config/nginx.conf
        target: /src/nginx.conf

      
   
    depends_on:
      - nodejs
    networks:
      - app-network
volumes:
  web-root:

networks:
  app-network:
    driver: bridge
